version: 0.1

phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:$NODE_ENV
artifacts:
  files:
    - ./dist
  # post_build:
  #   commands:
  #     - aws s3 sync ./dist $S3_BUCKET 